services:
  studio:
    build: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - HOST=${HOST}
      - PORT=${PORT}

      - BASE_URL=${BASE_URL}
      - SSL_PREFIX=${SSL_PREFIX}
      - SELF_HOSTED=${SELF_HOSTED}

      - DATABASE_URL=${DATABASE_URL}

      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

      - EXTERNAL_FUNCTIONS_URL=${EXTERNAL_FUNCTIONS_URL}

      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}

      - GARBAGE_CLEANER_CRON=${GARBAGE_CLEANER_CRON}
      - GARBAGE_CLEANER_FUNCTION=${GARBAGE_CLEANER_FUNCTION}